### ISSUE TITLE
Need For Speed Most Wanted 2005 Config

### ISSUE THREAD

**Issue by MarioTainaka** [samuelgr/XidiGameConfigurations#3]
Hi there! i've been following this project for quite a while. You're doing great work first of all. You're making enjoying retro games alot easier. Would you mind making a config for Need For Speed Most Wanted and the other black box games? I usually use the widescreen mod by thirteen ag with the gamepad support fix. While that combo works buttons show up wrong when mapping and it seems that pressure sensitive triggers don't work even when using the Xinput style mapper. Won't you mind making a fool proof config. Thanks again!

**Comment by samuelgr** [comment]
Glad to hear you've been enjoying Xidi :)

Unfortunately, I do not have access to that particular game so I cannot make a configuration for it and then test it properly. You (or anyone else who has the game) are welcome to do so and then submit it here.
